version: '3.9'
services:
  gatling:
    build: .
    environment:
      - HOSTS=http://host.docker.internal:8080/,http://host.docker.internal:8081/
      - ENDPOINTS=text,text/50
    volumes:
      - /tmp:/opt/gatling/results/
