version: '3.9'
services:
  gatling:
    build: .
    environment:
      - HOSTS=${WEBMVC_HOST},${WEBFLUX_HOST}
      - ENDPOINTS=text,text/50,remote/20?server=${REMOTE_WEBMVC_HOST}text/30,remote/20?server=${REMOTE_WEBFLUX_HOST}text/30
    volumes:
      - /tmp:/opt/gatling/results/
